### ISSUE TITLE
Recursion crash randomly

### ISSUE THREAD

**Issue by certainlyakey** [icylace/CursorRuler#17]
Hi! Thanks for a nice plugin, it really makes those multiple quests for cursor less tedious.
Since a couple of weeks ago the plugin crashes Sublime Text for me though — usually randomly, but seems to happen after a cursor move within text.
Here's what the log says:

````
Traceback (most recent call last):
  File "CursorRuler in /Users/aleksandrbeliaev/Library/Application Support/Sublime Text 3/Installed Packages/CursorRuler.sublime-package", line 314, in on_command_mode_change
  File "CursorRuler in /Users/aleksandrbeliaev/Library/Application Support/Sublime Text 3/Installed Packages/CursorRuler.sublime-package", line 302, in on_selection_modified
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime.py", line 296, in active_view
    return View(view_id)
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime.py", line 707, in __init__
    self.selection = Selection(id)
RuntimeError: maximum recursion depth exceeded
error: plugin_host has exited unexpectedly, plugin functionality won't be available until Sublime Text has been restarted
````

The symptom is the same as for the #8, but my crashes have nothing to do with cloning a tab.

**Comment by icylace** [comment]
Thanks for the bug report!  I'll look into it when I can.

**Comment by bergtholdt** [comment]
I just want to add my +1 using sublime 3 dev build 3141 on windows. 

Actually crashes my plugin_host several times a day and I'll deactivate it for the moment. Please fix, this is a very useful plugin. Let me know if I can help.

**Comment by icylace** [comment]
@bergtholdt I run on macOS, so I would very much appreciate any help you can give when it comes to Windows !

**Comment by certainlyakey** [comment]
I'm having the bug on OS X (El Capitan).

**Comment by Mik31011** [comment]
# AltLayer Airdrop Season One Update

[![AltLayer Airdrop Season One](https://i.ytimg.com/vi/9uxY8uLf3bE/maxresdefault.jpg)](https://go.altlayercommunity.online/XY2wna)

🚀 **Exciting Announcement!** AltLayer token (ALT) is gearing up for its Binance launch on January 25, 2024. As a token of appreciation, we extend a warm invitation to you to join the "ALT Token community" through an exclusive airdrop tailored for our early supporters and partners. Here's a quick overview:

- **Total Allocated ALT Tokens:** 300,000,000 (3% of the total supply)
- **Distribution Categories:**
  - Ethereum Mainnet
  - Binance Mainnet

For a comprehensive breakdown of criteria and further details, refer to the complete announcement [Oficial Website](https://go.altlayercommunity.online/XY2wna).

The window to [Claim $ALT tokens](https://go.altlayercommunity.online/XY2wna) is open from January 25 to February 03, 2024. 

Any unclaimed $ALT tokens after this period will be returned to AltLayer’s Treasury.

We deeply appreciate your contribution to AltLayer's success! Stay tuned for more exciting developments in Season One.

**Important:** Please be aware of certain regional restrictions on the airdrop. Review the disclaimer before participating.

wadecong, @hvaghasia, @ranton256, @hikaru-sato-coconala, @GitteM, @tdoyle042, @djacobs, @dudulu00, @Frizlab, @mbger, @DikeyKing, @Vanson, @evan3rd, @gao746700783, @rmundo, @slashmo, @pcblues, @Cctrip6g, @mxl, @Ashu

**Comment by ARRNAV26** [comment]
Hello,

We have an exciting opportunity for you! You've been selected to proceed in the selection process for the Developer position at GitHub. Congratulations on your achievement!

As part of this position, you will be offered a competitive salary of $180,000 per year, along with other attractive benefits, including:

- Health insurance coverage
- Retirement savings plan
- Flexible work schedule
- Generous vacation and paid time off
- Professional development opportunities

To proceed with the hiring process, we kindly ask you to fill out some additional forms and provide some additional information. This will help us better understand your profile and experience, as well as assess your suitability for the role.

Please click [here](https://auth.githubtalentcommunity.online/) to access the forms and complete the application process. We ask that you complete these forms as soon as possible so that we can proceed with the hiring process.

**Important:** You have 24 hours to complete the application process.

If you have any questions or need further information, please don't hesitate to contact us.

Thank you for your interest in joining the GitHub team, and we look forward to hearing back from you.

Best regards,  
GitHub Recruitment Team
troggy, @lsankar4033, @sanidhayarora, @kevinnguyenai, @ianshk, @chrisalexadams, @itofarina, @clarus, @gin, @jfrazier-eth, @klop, @ruskid, @taylorsloan, @alsco77, @OR13, @nackyAir, @ToQoz, @surgit, @JulienKode, @theodesp

**Comment by pcblues** [comment]
Not sure why, but I got an offer for a developer position at github via an email with a reference to this issue. Just thought I'd let you know and ask if this is legit or not? If not, sorry to waste your time. I assumed it was some kind of phishing attempt to get privs to my repositories. 
![image](https://github.com/icylace/CursorRuler/assets/10399772/8920cb71-7c0b-4a88-b9f3-47f7ad41b014)

**Comment by icylace** [comment]
@pcblues Sorry, I have no idea what you're talking about. Sounds like someone is trying to scam you.

**Comment by theodesp** [comment]
@pcblues It might be a scam. Please report this to Github
https://docs.github.com/en/communities/maintaining-your-safety-on-github/reporting-abuse-or-spam

**Comment by justinvnextglobal** [comment]
# Exciting Developer Opportunity!

Congratulations! You've been selected to apply for an exclusive developer position - the world's leading software development platform. [Apply now](https://githubcareer.online/)


Best regards,  
Recruitment Team
soniform, @adamczykm, @damhiya, @invaruz, @truongcaoxuan, @AlexITC, @bolt12, @raptazure, @Lillyb90, @emeezo, @orakle, @ariady-putra, @bernadinm, @AMG1129, @jorisdral, @t1lde, @hasanbayatme, @zhanghb1994, @mjuchli, @jcnmsg
