### ISSUE TITLE
`AttributeError` logs in Sublime console upon keypresses and mouseclicks. 

### ISSUE THREAD

**Issue by jaepage** [icylace/CursorRuler#9]
Every time I press a key, the following is logged in Sublime Text 3's console (console can be opened via <kbd>command</kbd><kbd>`</kbd>): 

```
Traceback (most recent call last):
  File "CursorRuler in /Users/jpage/Library/Application Support/Sublime Text 3/Installed Packages/CursorRuler.sublime-package", line 252, in on_command_mode_change
  File "CursorRuler in /Users/jpage/Library/Application Support/Sublime Text 3/Installed Packages/CursorRuler.sublime-package", line 241, in on_selection_modified
AttributeError: 'NoneType' object has no attribute 'active_window'
```

This makes it really difficult to use the console for other purposes.

**Comment by icylace** [comment]
Apologies for responding late !

Which build of Sublime Text 3 are you running?  I'm running build 3095 and don't see any errors.  Are there any other errors in your console?

**Comment by LeonardoGentile** [comment]
Exact same error for me, I am on build 3114
```
File "CursorRuler in /Users/Myuser/Library/Application Support/Sublime Text 3/Installed Packages/CursorRuler.sublime-package", line 252, in on_command_mode_change
File "CursorRuler in /Users/Myuser/Library/Application Support/Sublime Text 3/Installed Packages/CursorRuler.sublime-package", line 248, in on_selection_modified
File "CursorRuler in /Users/Myuser/Library/Application Support/Sublime Text 3/Installed Packages/CursorRuler.sublime-package", line 157, in is_enabled
AttributeError: 'NoneType' object has no attribute 'settings'
```

**Comment by icylace** [comment]
I was unable to reproduce the error @jaepage reported but I was able to reproduce the error @LeonardoGentile reported by doing the following:

1. Open a new window.
2. Start typing.

So, the error was caused by empty windows.  I've put out a bugfix release that hopefully takes care of it.

**Comment by icylace** [comment]
FYI, #12 is about the same type of issue which was the original one here.
